import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";
import path from "path";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the source code files.
*/`;

const prod = (process.argv[2] === "production");

const vaultPluginDir = 'C:/Users/dlrud/OneDrive/문서/obsidian/mig8128/.obsidian/plugins/obsidian-day-planner-pro';

esbuild.build({
	banner: {
		js: banner,
	},
	entryPoints: ["main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@electron/remote",
		...builtins],
	format: "cjs",
	target: "es2020",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
}).then(() => {
	if (fs.existsSync(vaultPluginDir)) {
		fs.copyFileSync("main.js", path.join(vaultPluginDir, "main.js"));
		fs.copyFileSync("manifest.json", path.join(vaultPluginDir, "manifest.json"));
		console.log("Successfully copied main.js and manifest.json to vault plugin directory.");
	}
}).catch(() => process.exit(1));